#include "ultrasonic.h"
#include "gpio.h"
#include "icu.h"
#include "util/delay.h"
#include "common_macros.h"
#include <avr/io.h>
uint8 g_edgeCount=0 ;
uint16 g_timeHigh=0 ;

/* • Description
➢ Initialize the ICU driver as required.
➢ Setup the ICU call back function.
➢ Setup the direction for the trigger pin as output pin through the GPIO driver.
*/
void Ultrasonic_init(void){
	Icu_ConfigType ptr = {F_CPU_8,RISING};
	Icu_init(&ptr);
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(PORTB_ID, PIN5_ID, PIN_OUTPUT);
}

/* • Description
➢ Send the Trigger pulse to the ultrasonic.
*/
void Ultrasonic_Trigger(void){
	GPIO_writePin(PORTB_ID, PIN5_ID, 1);
	_delay_us(10);
	GPIO_writePin(PORTB_ID, PIN5_ID, 0);
}

/* • Description
➢ Send the trigger pulse by using Ultrasonic_Trigger function.
➢ Start the measurements by the ICU from this moment.
• Inputs: None
• Return: The measured distance in Centimeter.
*/
uint16 Ultrasonic_readDistance(void){
	Ultrasonic_Trigger();
	uint16 distance;
	while(g_edgeCount != 2);
	g_edgeCount = 0;
	distance = (g_timeHigh/58.8);
	return distance;
}

/* • Description
➢ This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
*/
void Ultrasonic_edgeProcessing(void){
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
	}
}
